# Generated by Django 3.1.1 on 2020-09-25 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('large_proj', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='large_proj',
            name='para_one_link',
        ),
        migrations.RemoveField(
            model_name='large_proj',
            name='para_two_img1',
        ),
        migrations.RemoveField(
            model_name='large_proj',
            name='para_two_img2',
        ),
        migrations.RemoveField(
            model_name='large_proj',
            name='para_two_img3',
        ),
        migrations.RemoveField(
            model_name='large_proj',
            name='para_two_img4',
        ),
        migrations.AddField(
            model_name='large_proj',
            name='para_one_img',
            field=models.CharField(default='https://i.imgur.com/e4zkPkY.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='para_three_copy',
            field=models.CharField(default='Copy content', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='para_three_img',
            field=models.CharField(default='https://i.imgur.com/e4zkPkY.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='para_three_title',
            field=models.CharField(default='Title', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='para_two_img',
            field=models.CharField(default='https://i.imgur.com/e4zkPkY.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='proj_desc',
            field=models.CharField(default='Copy content', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='proj_img',
            field=models.CharField(default='https://i.imgur.com/e4zkPkY.jpg', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='skills',
            field=models.CharField(default='UX, design & development', max_length=400),
        ),
        migrations.AddField(
            model_name='large_proj',
            name='url',
            field=models.CharField(default='https://www.google.com/', max_length=400),
        ),
        migrations.AlterField(
            model_name='large_proj',
            name='para_one_copy',
            field=models.CharField(default='Copy content', max_length=400),
        ),
        migrations.AlterField(
            model_name='large_proj',
            name='para_one_title',
            field=models.CharField(default='Title', max_length=400),
        ),
        migrations.AlterField(
            model_name='large_proj',
            name='para_two_copy',
            field=models.CharField(default='Copy content', max_length=400),
        ),
        migrations.AlterField(
            model_name='large_proj',
            name='para_two_title',
            field=models.CharField(default='Title', max_length=400),
        ),
    ]
