# Generated by Django 3.1.1 on 2020-09-25 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('large_proj', '0002_auto_20200925_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='large_proj',
            name='proj_title',
            field=models.CharField(default='Project 1', max_length=400),
        ),
    ]
