# Generated by Django 3.1.1 on 2020-09-25 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('large_proj', '0003_large_proj_proj_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='large_proj',
            name='url2',
            field=models.CharField(default='https://www.google.com/', max_length=400),
        ),
    ]
