# Generated by Django 3.1.1 on 2020-09-24 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proj_short_title', models.CharField(max_length=60)),
                ('proj_short_copy', models.CharField(max_length=400)),
                ('proj_short_img', models.CharField(max_length=200)),
                ('proj_short_link1', models.CharField(max_length=100)),
                ('proj_short_link2', models.CharField(max_length=100)),
            ],
        ),
    ]
