# Generated by Django 3.1.1 on 2020-09-24 10:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('small_proj', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pokemon',
            new_name='Small_proj',
        ),
    ]
